name: oci-build

on:
  push:
    branches: [ main ]
    tags:        
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-frdp
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image
      shell: bash
      run: make oci-build

    - name: Log in to quay.io Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Push image
      shell: bash
      run: make oci-push
        
